### ISSUE TITLE
new syntax for css gradients in webkit

### ISSUE THREAD

**Issue by thelitek** [dancrew32/lesslib#2]
Webkit introduced new sytax for gradients. Old one is still supported and probably will be for quite a long time, nevertheless I think it should be added here. The new syntax looks like the one mozilla uses. 
Source: http://www.webkit.org/blog/1424/css3-gradients/

**Comment by dancrew32** [comment]
awesome, I'll get that included asap. Thanks for contributing

**Comment by dancrew32** [comment]
should be in now with: https://github.com/dancrew32/lesslib/commit/124ed88f13f0b1a22b593e7d6ac94c42c4ae352a

I think the next commit will have an optional 3rd argument for a fallback gradient image repeating x or y (horizontal/veritcal), but I think this should close the ticket!

Please keep adding issues! Thanks for your help!
